name: imsmart_admin
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fluttericon: ^2.0.0
  provider: ^6.0.5
  get_it: ^8.0.3
  http: ^1.2.2
  cached_network_image: ^3.1.0
  image_picker: ^1.1.2
  image_cropper: ^8.1.0
  shimmer: ^3.0.0
  qr_flutter: ^4.0.0
  flutter_svg: ^2.0.16
  intl: ^0.19.0
  sqflite: ^2.0.0+3
  flutter_screenutil: ^5.0.0+2
  pin_input_text_field:
  numeric_keyboard:
  adaptive_theme:
  path_provider: ^2.1.5
  url_launcher:
  flip_card:
  camera:
  badges:
#  share:
  gap: ^3.0.1
  get: ^4.6.5
  country_code_picker: ^3.1.0
  country_pickers: ^3.0.1
  auto_size_text: ^3.0.0-nullsafety.0
  currency_text_input_formatter: ^2.1.2
  flutter_typeahead: ^5.2.0
  permission_handler: ^11.3.1
  #flutter_paystack: ^1.0.5+1
  cloudinary_sdk: ^5.0.0+1
  flutter_secure_storage: ^9.2.2
  firebase_core: ^3.8.1
  #firebase_core_platform_interface: 4.5.1
  firebase_messaging: ^15.1.6
  #platform_device_id: ^1.0.1
  device_info_plus: ^11.2.0
  upgrader: ^11.3.1
  firebase_dynamic_links: ^6.0.11
  firebase_crashlytics: ^4.2.0
  #  flutter_custom_dialog: ^1.3.0
  circular_profile_avatar: ^2.0.5
  lottie: ^3.2.0
  image: ^4.3.0
  date_time_format: ^2.0.1
  group_radio_button: ^1.2.0
  screenshot: ^3.0.0
#  share_files_and_screenshot_widgets: ^1.0.6
  injectable: ^2.1.0
  dio: ^5.7.0
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  theme_manager: ^1.1.0
  equatable: ^2.0.3
  firebase_analytics:
  event_bus: ^2.0.0
  flutter_spinkit: ^5.1.0
  route_animation_helper: ^2.0.0+7
  fluttertoast: ^8.0.8
  google_fonts: ^6.2.1
  pin_code_fields: ^8.0.1
  pull_to_refresh: ^2.0.0
  photo_view: ^0.15.0
  sticky_grouped_list: ^3.1.0
  timeago: ^3.2.2
  # multi_image_picker2: ^5.0.2
  flutter_image_slideshow: ^0.1.6
  package_info_plus: ^8.1.2
  share_plus: ^10.1.3
  geocoding: ^2.1.1
  flutter_widget_from_html_core:
  maps_launcher: ^2.2.0
  swipeable_page_route: ^0.4.4
  flutter_shakemywidget: ^1.0.5+1
  choose_input_chips: ^1.1.3
  webview_flutter:
  in_app_review: ^2.0.10

dependency_overrides:
  intl: ^0.17.0
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons:
  change_app_package_name: ^1.1.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "asset/images/app_icon.png"
  ipad: true
  image_path_ipad: "asset/images/ipad_icon.png"
  image_path_ipad_2x: "asset/images/ipad_icon@2x.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/images/
    - asset/lottie/
    - asset/svgs/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: helvetica
      fonts:
        - asset: asset/fonts/HelveticaNeueLTStd-Lt.otf

    - family: helveticabold
      fonts:
        - asset: asset/fonts/HelveticaNeueLTStd-Bd.otf

    - family: PoppinsRegular
      fonts:
        - asset: asset/fonts/poppins.regular.ttf
        - asset: asset/fonts/poppins.medium.ttf
        - asset: asset/fonts/poppins.black.ttf
        - asset: asset/fonts/poppins.light.ttf
        - asset: asset/fonts/poppins.bold.ttf
        - asset: asset/fonts/poppins.semibold.ttf
          style: normal

    - family: PoppinsItalic
      fonts:
        - asset: asset/fonts/poppins.medium.ttf
        - asset: asset/fonts/poppins.italic.ttf
          style: italic

    - family: SFProDisplayRegular
      fonts:
        #        - asset: asset/fonts/SF-Pro-Display-Ultralight.ttf
        #          weight: 100
        #          style: normal
        #        - asset: asset/fonts/SF-Pro-Display-Regular.ttf
        #          style: normal
        - asset: asset/fonts/SF-Pro-Display-Medium.ttf
          style: normal
    #        - asset: asset/fonts/SF-Pro-Display-Bold.ttf
    #          weight: 400
    #          style: normal
    #        - asset: asset/fonts/SF-Pro-Display-Heavy.ttf
    #          weight: 500
    #          style: normal
    #        - asset: asset/fonts/SF-Pro-Display-Black.ttf
    #          weight: 600
    #          style: normal

    - family: SFProDisplayItalic
      fonts:
        - asset: asset/fonts/SF-Pro-Display-UltralightItalic.ttf
        - asset: asset/fonts/SF-Pro-Display-ThinItalic.ttf
        - asset: asset/fonts/SF-Pro-Display-HeavyItalic.ttf
          style: italic

    - family: BrittanySignature
      fonts:
        - asset: asset/fonts/BrittanySignature.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
