/// Flutter icons BlinkCashIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BlinkCashIcon
///      fonts:
///       - asset: fonts/BlinkCashIcon.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class BlinkCashIcon {
  BlinkCashIcon._();

  static const _kFontFam = 'BlinkCash';
  static const String? _kFontPkg = null;

  static const IconData biometric = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData faceid = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData illustration = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData loan = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData get_loan = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pay = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_circle = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData save = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData questionmarkcirlce = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person_add = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transfer = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData adduser = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bank = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bigdevice = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData changepin = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData device = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feedback = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fundtransfer = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keylock = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData onlinetransfer = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paybill = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_1 = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData questionmark = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData security = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sendmoney = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
